### ISSUE TITLE
Similar framework

### ISSUE THREAD

**Issue by linsyking** [Zinggi/elm-2d-game#11]
I wrote a 2D Elm game framework called [Messenger](https://github.com/linsyking/Messenger) and it has many nice features.

Our team developed a game called [Reweave](https://github.com/linsyking/Reweave) based on this framework.

Your 2d game library is great, but I think Messenger works better when creating a complex games (it's modularized, object-oriented).

I would appreciate if you could let me add a link to my project in your Readme. I hope that more people can see my framework :)

Hope you like our framework & game!

**Comment by Zinggi** [comment]
Hey, that looks like a very cool project, well done!

There are many alternative game dev libraries for Elm, so I don't just want to single out a few of them here.
But since my library didn't got any update in the last couple of years, I thought it does make sense to link to some alternatives from the readme. 
So I now added a small section to link to https://korban.net/elm/catalog/packages/game-dev/rendering, which has a pretty good selection.

Your project isn't there yet, but I think you can just [contact Alex](https://korban.net/elm/contact/) and he'll probably add it.



Btw, the link to your demo doesn't work anymore for me, it worked 2 days ago though when I read your message first and it made a pretty good impression


(closing this as it's not an 'issue')
