### ISSUE TITLE
Plugin naming convention

### ISSUE THREAD

**Issue by schoening** [Zinggi/elm-2d-game#5]
Hi, this is a super minor thing, but I saw you want plugins to be named elm-game-2d-<plugin-name>.
I am very new to Elm but is there any reason not to call them elm-game-2d/<plugin-name> ? 
I think that would make it a little more obvious if a package is part of elm-game-2d.

**Comment by Zinggi** [comment]
Hi @schoening,

I guess you are referring to the "vision" section in the readme?

> I am very new to Elm but is there any reason not to call them elm-game-2d/

I have never seen any elm package that uses a slash in its name, I don't know if that would even be allowed.
Elm packages are organized by github user/organization, so the `/` might be reserved for separating the username from package names.    

Have you seen this used elsewhere in the elm community? If so, I'm open to change that in the readme.

---
(I'm closing this issue since it's just a question, don't interpret this a closing the discussion, feel free to keep chatting)

**Comment by schoening** [comment]
Oh I see. Like I say I am new to Elm. I saw the packages like elm-explorations/webgl and thought its namespacing and not the username. Learned something new today, should have asked on the chat first.

**Comment by Zinggi** [comment]
No worries, welcome to the Elm community!
